//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AppEntities : DbContext
    {
        public object tblSC_Appointment;

        public AppEntities()
            : base("name=AppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
    		modelBuilder.Properties<DateTime>().Configure(c => c.HasColumnType("datetime2"));
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_AC_JournalEntry> tbl_AC_JournalEntry { get; set; }
        public virtual DbSet<tbl_AC_JournalEntryRow> tbl_AC_JournalEntryRow { get; set; }
        public virtual DbSet<tbl_AC_PostingPeriod> tbl_AC_PostingPeriod { get; set; }
        public virtual DbSet<tbl_BANK_IncomingPayment> tbl_BANK_IncomingPayment { get; set; }
        public virtual DbSet<tbl_BANK_IncomingPaymentDetail> tbl_BANK_IncomingPaymentDetail { get; set; }
        public virtual DbSet<tbl_BANK_PaymentTerm> tbl_BANK_PaymentTerm { get; set; }
        public virtual DbSet<tbl_BC_RevenueExpenditureComponent> tbl_BC_RevenueExpenditureComponent { get; set; }
        public virtual DbSet<tbl_BC_RevenueExpenditureRefCode> tbl_BC_RevenueExpenditureRefCode { get; set; }
        public virtual DbSet<tbl_BI_Finance_BalanceSheetCategory> tbl_BI_Finance_BalanceSheetCategory { get; set; }
        public virtual DbSet<tbl_BI_Finance_BalanceSheets> tbl_BI_Finance_BalanceSheets { get; set; }
        public virtual DbSet<tbl_BI_Finance_CashFlow> tbl_BI_Finance_CashFlow { get; set; }
        public virtual DbSet<tbl_BI_Finance_IncomeStatement> tbl_BI_Finance_IncomeStatement { get; set; }
        public virtual DbSet<tbl_BI_Finance_Management> tbl_BI_Finance_Management { get; set; }
        public virtual DbSet<tbl_BI_Operating_MarketResearch> tbl_BI_Operating_MarketResearch { get; set; }
        public virtual DbSet<tbl_BI_Oppotunity> tbl_BI_Oppotunity { get; set; }
        public virtual DbSet<tbl_BI_ReportTemplate> tbl_BI_ReportTemplate { get; set; }
        public virtual DbSet<tbl_BI_ReportTemplateDetail> tbl_BI_ReportTemplateDetail { get; set; }
        public virtual DbSet<tbl_BP_Partner> tbl_BP_Partner { get; set; }
        public virtual DbSet<tbl_BRA_Branch> tbl_BRA_Branch { get; set; }
        public virtual DbSet<tbl_BSC_RevenueTarget> tbl_BSC_RevenueTarget { get; set; }
        public virtual DbSet<tbl_CRM_Activity> tbl_CRM_Activity { get; set; }
        public virtual DbSet<tbl_CRM_Attendance> tbl_CRM_Attendance { get; set; }
        public virtual DbSet<tbl_CRM_BusinessPartnerGroup> tbl_CRM_BusinessPartnerGroup { get; set; }
        public virtual DbSet<tbl_CRM_Campaign> tbl_CRM_Campaign { get; set; }
        public virtual DbSet<tbl_CRM_CampaignMember> tbl_CRM_CampaignMember { get; set; }
        public virtual DbSet<tbl_CRM_Config> tbl_CRM_Config { get; set; }
        public virtual DbSet<tbl_CRM_Contact> tbl_CRM_Contact { get; set; }
        public virtual DbSet<tbl_CRM_ContactReference> tbl_CRM_ContactReference { get; set; }
        public virtual DbSet<tbl_CRM_Contract> tbl_CRM_Contract { get; set; }
        public virtual DbSet<tbl_CRM_Customer> tbl_CRM_Customer { get; set; }
        public virtual DbSet<tbl_CRM_Lead> tbl_CRM_Lead { get; set; }
        public virtual DbSet<tbl_CRM_Opportunity> tbl_CRM_Opportunity { get; set; }
        public virtual DbSet<tbl_CRM_Outlets> tbl_CRM_Outlets { get; set; }
        public virtual DbSet<tbl_CRM_PartnerAddress> tbl_CRM_PartnerAddress { get; set; }
        public virtual DbSet<tbl_CRM_PartnerBankAccount> tbl_CRM_PartnerBankAccount { get; set; }
        public virtual DbSet<tbl_CRM_PersonInfo> tbl_CRM_PersonInfo { get; set; }
        public virtual DbSet<tbl_CRM_Quotation> tbl_CRM_Quotation { get; set; }
        public virtual DbSet<tbl_CRM_Route> tbl_CRM_Route { get; set; }
        public virtual DbSet<tbl_CRM_RouteDetail> tbl_CRM_RouteDetail { get; set; }
        public virtual DbSet<tbl_FINANCE_GeneralLedger> tbl_FINANCE_GeneralLedger { get; set; }
        public virtual DbSet<tbl_FINANCE_TaxDefinition> tbl_FINANCE_TaxDefinition { get; set; }
        public virtual DbSet<tbl_HRM_DeductionOnSalary> tbl_HRM_DeductionOnSalary { get; set; }
        public virtual DbSet<tbl_HRM_PayrollElement> tbl_HRM_PayrollElement { get; set; }
        public virtual DbSet<tbl_HRM_PayrollPaySheetMaster> tbl_HRM_PayrollPaySheetMaster { get; set; }
        public virtual DbSet<tbl_HRM_PayrollPaySheetMasterSalaryDecision> tbl_HRM_PayrollPaySheetMasterSalaryDecision { get; set; }
        public virtual DbSet<tbl_HRM_PersonalIncomePaymentProcess> tbl_HRM_PersonalIncomePaymentProcess { get; set; }
        public virtual DbSet<tbl_HRM_PolAllowance> tbl_HRM_PolAllowance { get; set; }
        public virtual DbSet<tbl_HRM_PolAllowanceApplyFor> tbl_HRM_PolAllowanceApplyFor { get; set; }
        public virtual DbSet<tbl_HRM_PolCompulsoryInsurance> tbl_HRM_PolCompulsoryInsurance { get; set; }
        public virtual DbSet<tbl_HRM_PolCompulsoryInsuranceApplyFor> tbl_HRM_PolCompulsoryInsuranceApplyFor { get; set; }
        public virtual DbSet<tbl_HRM_PolicyHoliday> tbl_HRM_PolicyHoliday { get; set; }
        public virtual DbSet<tbl_HRM_PolicyPaidTimeOff> tbl_HRM_PolicyPaidTimeOff { get; set; }
        public virtual DbSet<tbl_HRM_PolicyPaidTimeOffGrantsByLengthOfServices> tbl_HRM_PolicyPaidTimeOffGrantsByLengthOfServices { get; set; }
        public virtual DbSet<tbl_HRM_PolWelfare> tbl_HRM_PolWelfare { get; set; }
        public virtual DbSet<tbl_HRM_PolWelfareApplyFor> tbl_HRM_PolWelfareApplyFor { get; set; }
        public virtual DbSet<tbl_HRM_Shift> tbl_HRM_Shift { get; set; }
        public virtual DbSet<tbl_HRM_Staff> tbl_HRM_Staff { get; set; }
        public virtual DbSet<tbl_HRM_Staff_ConcurrentPosition> tbl_HRM_Staff_ConcurrentPosition { get; set; }
        public virtual DbSet<tbl_HRM_StaffAcademicLevel> tbl_HRM_StaffAcademicLevel { get; set; }
        public virtual DbSet<tbl_HRM_StaffAddress> tbl_HRM_StaffAddress { get; set; }
        public virtual DbSet<tbl_HRM_StaffAllowance> tbl_HRM_StaffAllowance { get; set; }
        public virtual DbSet<tbl_HRM_StaffAnotherSkill> tbl_HRM_StaffAnotherSkill { get; set; }
        public virtual DbSet<tbl_HRM_StaffAppointDecision> tbl_HRM_StaffAppointDecision { get; set; }
        public virtual DbSet<tbl_HRM_StaffBank> tbl_HRM_StaffBank { get; set; }
        public virtual DbSet<tbl_HRM_StaffBasicInfo> tbl_HRM_StaffBasicInfo { get; set; }
        public virtual DbSet<tbl_HRM_StaffBounusOnSalary> tbl_HRM_StaffBounusOnSalary { get; set; }
        public virtual DbSet<tbl_HRM_StaffCompulsoryInsurance> tbl_HRM_StaffCompulsoryInsurance { get; set; }
        public virtual DbSet<tbl_HRM_StaffConcurrentProbationryPosition> tbl_HRM_StaffConcurrentProbationryPosition { get; set; }
        public virtual DbSet<tbl_HRM_StaffCurrentWorking> tbl_HRM_StaffCurrentWorking { get; set; }
        public virtual DbSet<tbl_HRM_StaffDeductionOnSalary> tbl_HRM_StaffDeductionOnSalary { get; set; }
        public virtual DbSet<tbl_HRM_StaffFamily> tbl_HRM_StaffFamily { get; set; }
        public virtual DbSet<tbl_HRM_StaffForeignLanguage> tbl_HRM_StaffForeignLanguage { get; set; }
        public virtual DbSet<tbl_HRM_StaffIdentityCardAndPIT> tbl_HRM_StaffIdentityCardAndPIT { get; set; }
        public virtual DbSet<tbl_HRM_StaffInsurancePaymentProcess> tbl_HRM_StaffInsurancePaymentProcess { get; set; }
        public virtual DbSet<tbl_HRM_StaffInternetAccount> tbl_HRM_StaffInternetAccount { get; set; }
        public virtual DbSet<tbl_HRM_StaffLaborContract> tbl_HRM_StaffLaborContract { get; set; }
        public virtual DbSet<tbl_HRM_StaffLearningProcess> tbl_HRM_StaffLearningProcess { get; set; }
        public virtual DbSet<tbl_HRM_StaffPhone> tbl_HRM_StaffPhone { get; set; }
        public virtual DbSet<tbl_HRM_StaffPTOEnrollment> tbl_HRM_StaffPTOEnrollment { get; set; }
        public virtual DbSet<tbl_HRM_StaffRecruitmentInfo> tbl_HRM_StaffRecruitmentInfo { get; set; }
        public virtual DbSet<tbl_HRM_StaffResignationInfo> tbl_HRM_StaffResignationInfo { get; set; }
        public virtual DbSet<tbl_HRM_StaffSalaryDecision> tbl_HRM_StaffSalaryDecision { get; set; }
        public virtual DbSet<tbl_HRM_StaffSpecializedField> tbl_HRM_StaffSpecializedField { get; set; }
        public virtual DbSet<tbl_HRM_StaffSpecializedSkill> tbl_HRM_StaffSpecializedSkill { get; set; }
        public virtual DbSet<tbl_HRM_StaffStaffAndFamilyJob> tbl_HRM_StaffStaffAndFamilyJob { get; set; }
        public virtual DbSet<tbl_HRM_StaffTrainingProcess> tbl_HRM_StaffTrainingProcess { get; set; }
        public virtual DbSet<tbl_HRM_StaffTrainingProcessSkill> tbl_HRM_StaffTrainingProcessSkill { get; set; }
        public virtual DbSet<tbl_HRM_StaffWelfare> tbl_HRM_StaffWelfare { get; set; }
        public virtual DbSet<tbl_HRM_StaffWorkExperience> tbl_HRM_StaffWorkExperience { get; set; }
        public virtual DbSet<tbl_HRM_StaffWorkingDiary> tbl_HRM_StaffWorkingDiary { get; set; }
        public virtual DbSet<tbl_HRM_TimeSheetCheckInCode> tbl_HRM_TimeSheetCheckInCode { get; set; }
        public virtual DbSet<tbl_HRM_TimeSheetLog> tbl_HRM_TimeSheetLog { get; set; }
        public virtual DbSet<tbl_LIST_ContractTemplate> tbl_LIST_ContractTemplate { get; set; }
        public virtual DbSet<tbl_LIST_Country> tbl_LIST_Country { get; set; }
        public virtual DbSet<tbl_LIST_District> tbl_LIST_District { get; set; }
        public virtual DbSet<tbl_LIST_ElementOfSalary> tbl_LIST_ElementOfSalary { get; set; }
        public virtual DbSet<tbl_LIST_General> tbl_LIST_General { get; set; }
        public virtual DbSet<tbl_LIST_PayPeriod> tbl_LIST_PayPeriod { get; set; }
        public virtual DbSet<tbl_LIST_Province> tbl_LIST_Province { get; set; }
        public virtual DbSet<tbl_LIST_Ward> tbl_LIST_Ward { get; set; }
        public virtual DbSet<tbl_MR_CompetiorOrder> tbl_MR_CompetiorOrder { get; set; }
        public virtual DbSet<tbl_MR_TrackingCompetitor> tbl_MR_TrackingCompetitor { get; set; }
        public virtual DbSet<tbl_OST_Office> tbl_OST_Office { get; set; }
        public virtual DbSet<tbl_OST_OfficeGate> tbl_OST_OfficeGate { get; set; }
        public virtual DbSet<tbl_PM_Task> tbl_PM_Task { get; set; }
        public virtual DbSet<tbl_PR_PromotionTracking> tbl_PR_PromotionTracking { get; set; }
        public virtual DbSet<tbl_PROD_BillOfMaterials> tbl_PROD_BillOfMaterials { get; set; }
        public virtual DbSet<tbl_PROD_BillOfMaterialsDetail> tbl_PROD_BillOfMaterialsDetail { get; set; }
        public virtual DbSet<tbl_PROD_ItemInVendor> tbl_PROD_ItemInVendor { get; set; }
        public virtual DbSet<tbl_PROD_MRP> tbl_PROD_MRP { get; set; }
        public virtual DbSet<tbl_PURCHASE_Order> tbl_PURCHASE_Order { get; set; }
        public virtual DbSet<tbl_PURCHASE_OrderDetail> tbl_PURCHASE_OrderDetail { get; set; }
        public virtual DbSet<tbl_SALE_Order> tbl_SALE_Order { get; set; }
        public virtual DbSet<tbl_SALE_OrderDetail> tbl_SALE_OrderDetail { get; set; }
        public virtual DbSet<tbl_SHIFT_TimeSheet> tbl_SHIFT_TimeSheet { get; set; }
        public virtual DbSet<tbl_SHIP_Shipment> tbl_SHIP_Shipment { get; set; }
        public virtual DbSet<tbl_SHIP_ShipmentDebt> tbl_SHIP_ShipmentDebt { get; set; }
        public virtual DbSet<tbl_SHIP_ShipmentDetail> tbl_SHIP_ShipmentDetail { get; set; }
        public virtual DbSet<tbl_SHIP_Vehicle> tbl_SHIP_Vehicle { get; set; }
        public virtual DbSet<tbl_SYS_Apps> tbl_SYS_Apps { get; set; }
        public virtual DbSet<tbl_SYS_Config> tbl_SYS_Config { get; set; }
        public virtual DbSet<tbl_SYS_ConfigOption> tbl_SYS_ConfigOption { get; set; }
        public virtual DbSet<tbl_SYS_Currency> tbl_SYS_Currency { get; set; }
        public virtual DbSet<tbl_SYS_DataPermissionList> tbl_SYS_DataPermissionList { get; set; }
        public virtual DbSet<tbl_SYS_Form> tbl_SYS_Form { get; set; }
        public virtual DbSet<tbl_SYS_FormGroup> tbl_SYS_FormGroup { get; set; }
        public virtual DbSet<tbl_SYS_GlobalConfig> tbl_SYS_GlobalConfig { get; set; }
        public virtual DbSet<tbl_SYS_Log> tbl_SYS_Log { get; set; }
        public virtual DbSet<tbl_SYS_PermissionList> tbl_SYS_PermissionList { get; set; }
        public virtual DbSet<tbl_SYS_Role> tbl_SYS_Role { get; set; }
        public virtual DbSet<tbl_SYS_RuningNo> tbl_SYS_RuningNo { get; set; }
        public virtual DbSet<tbl_SYS_SAP_Databases> tbl_SYS_SAP_Databases { get; set; }
        public virtual DbSet<tbl_SYS_Status> tbl_SYS_Status { get; set; }
        public virtual DbSet<tbl_SYS_SyncJob> tbl_SYS_SyncJob { get; set; }
        public virtual DbSet<tbl_SYS_Type> tbl_SYS_Type { get; set; }
        public virtual DbSet<tbl_SYS_UserDevice> tbl_SYS_UserDevice { get; set; }
        public virtual DbSet<tbl_SYS_UserSetting> tbl_SYS_UserSetting { get; set; }
        public virtual DbSet<tbl_SYS_UserVoice> tbl_SYS_UserVoice { get; set; }
        public virtual DbSet<tbl_SYS_VeifyPhoneNumber> tbl_SYS_VeifyPhoneNumber { get; set; }
        public virtual DbSet<tbl_Version> tbl_Version { get; set; }
        public virtual DbSet<tbl_WEB_Category> tbl_WEB_Category { get; set; }
        public virtual DbSet<tbl_WEB_Content> tbl_WEB_Content { get; set; }
        public virtual DbSet<tbl_WEB_Content_Tag> tbl_WEB_Content_Tag { get; set; }
        public virtual DbSet<tbl_WEB_ContentInCategory> tbl_WEB_ContentInCategory { get; set; }
        public virtual DbSet<tbl_WEB_Tag> tbl_WEB_Tag { get; set; }
        public virtual DbSet<tbl_WH_Branches> tbl_WH_Branches { get; set; }
        public virtual DbSet<tbl_WH_CashFlows> tbl_WH_CashFlows { get; set; }
        public virtual DbSet<tbl_WH_ContactGroups> tbl_WH_ContactGroups { get; set; }
        public virtual DbSet<tbl_WH_Contacts> tbl_WH_Contacts { get; set; }
        public virtual DbSet<tbl_WH_GeneralLedgers> tbl_WH_GeneralLedgers { get; set; }
        public virtual DbSet<tbl_WH_Invoices> tbl_WH_Invoices { get; set; }
        public virtual DbSet<tbl_WH_ItemGroups> tbl_WH_ItemGroups { get; set; }
        public virtual DbSet<tbl_WH_ItemPriceLists> tbl_WH_ItemPriceLists { get; set; }
        public virtual DbSet<tbl_WH_Items> tbl_WH_Items { get; set; }
        public virtual DbSet<tbl_WH_ItemUoM> tbl_WH_ItemUoM { get; set; }
        public virtual DbSet<tbl_WH_JournalEntries> tbl_WH_JournalEntries { get; set; }
        public virtual DbSet<tbl_WH_JournalEntryRows> tbl_WH_JournalEntryRows { get; set; }
        public virtual DbSet<tbl_WH_PostingPeriods> tbl_WH_PostingPeriods { get; set; }
        public virtual DbSet<tbl_WH_PriceLists> tbl_WH_PriceLists { get; set; }
        public virtual DbSet<tbl_WH_Staff> tbl_WH_Staff { get; set; }
        public virtual DbSet<tbl_WH_UoM> tbl_WH_UoM { get; set; }
        public virtual DbSet<tbl_WH_VTB_Statements> tbl_WH_VTB_Statements { get; set; }
        public virtual DbSet<tbl_WMS_Adjustment> tbl_WMS_Adjustment { get; set; }
        public virtual DbSet<tbl_WMS_AdjustmentDetail> tbl_WMS_AdjustmentDetail { get; set; }
        public virtual DbSet<tbl_WMS_Carrier> tbl_WMS_Carrier { get; set; }
        public virtual DbSet<tbl_WMS_Carton> tbl_WMS_Carton { get; set; }
        public virtual DbSet<tbl_WMS_CartonGroup> tbl_WMS_CartonGroup { get; set; }
        public virtual DbSet<tbl_WMS_Item> tbl_WMS_Item { get; set; }
        public virtual DbSet<tbl_WMS_ItemGroup> tbl_WMS_ItemGroup { get; set; }
        public virtual DbSet<tbl_WMS_ItemInLocation> tbl_WMS_ItemInLocation { get; set; }
        public virtual DbSet<tbl_WMS_ItemInWarehouseConfig> tbl_WMS_ItemInWarehouseConfig { get; set; }
        public virtual DbSet<tbl_WMS_ItemUoM> tbl_WMS_ItemUoM { get; set; }
        public virtual DbSet<tbl_WMS_LicencePlateNumber> tbl_WMS_LicencePlateNumber { get; set; }
        public virtual DbSet<tbl_WMS_Location> tbl_WMS_Location { get; set; }
        public virtual DbSet<tbl_WMS_Lot> tbl_WMS_Lot { get; set; }
        public virtual DbSet<tbl_WMS_LotAttribute> tbl_WMS_LotAttribute { get; set; }
        public virtual DbSet<tbl_WMS_LotLPNLocation> tbl_WMS_LotLPNLocation { get; set; }
        public virtual DbSet<tbl_WMS_PriceList> tbl_WMS_PriceList { get; set; }
        public virtual DbSet<tbl_WMS_PriceListDetail> tbl_WMS_PriceListDetail { get; set; }
        public virtual DbSet<tbl_WMS_PriceListVersion> tbl_WMS_PriceListVersion { get; set; }
        public virtual DbSet<tbl_WMS_PriceListVersionDetail> tbl_WMS_PriceListVersionDetail { get; set; }
        public virtual DbSet<tbl_WMS_PutawayStrategy> tbl_WMS_PutawayStrategy { get; set; }
        public virtual DbSet<tbl_WMS_PutawayStrategyDetail> tbl_WMS_PutawayStrategyDetail { get; set; }
        public virtual DbSet<tbl_WMS_Receipt> tbl_WMS_Receipt { get; set; }
        public virtual DbSet<tbl_WMS_ReceiptDetail> tbl_WMS_ReceiptDetail { get; set; }
        public virtual DbSet<tbl_WMS_ReceiptPalletization> tbl_WMS_ReceiptPalletization { get; set; }
        public virtual DbSet<tbl_WMS_Storer> tbl_WMS_Storer { get; set; }
        public virtual DbSet<tbl_WMS_TaskDispatchStrategy> tbl_WMS_TaskDispatchStrategy { get; set; }
        public virtual DbSet<tbl_WMS_TaskDispatchStrategyDetail> tbl_WMS_TaskDispatchStrategyDetail { get; set; }
        public virtual DbSet<tbl_WMS_Transaction> tbl_WMS_Transaction { get; set; }
        public virtual DbSet<tbl_WMS_UoM> tbl_WMS_UoM { get; set; }
        public virtual DbSet<tbl_WMS_UoMGroup> tbl_WMS_UoMGroup { get; set; }
        public virtual DbSet<tbl_WMS_Vendor> tbl_WMS_Vendor { get; set; }
        public virtual DbSet<tbl_WMS_WarehouseInfo> tbl_WMS_WarehouseInfo { get; set; }
        public virtual DbSet<tbl_WMS_WavePlanning> tbl_WMS_WavePlanning { get; set; }
        public virtual DbSet<tbl_WMS_Zone> tbl_WMS_Zone { get; set; }
        public virtual DbSet<tbl_HRM_StaffConcurrentPosition> tbl_HRM_StaffConcurrentPosition { get; set; }
    
        public virtual int ExecJobs()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ExecJobs");
        }
    
        [DbFunction("AppEntities", "fnGetRootItemGroup")]
        public virtual IQueryable<fnGetRootItemGroup_Result> fnGetRootItemGroup(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnGetRootItemGroup_Result>("[AppEntities].[fnGetRootItemGroup](@Id)", idParameter);
        }
    }
}
