//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class API_Branches
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Phone { get; set; }
        public string Phone2 { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string URL { get; set; }
        public Nullable<int> Color1 { get; set; }
        public Nullable<int> Color2 { get; set; }
        public Nullable<int> Color3 { get; set; }
        public Nullable<int> Color4 { get; set; }
        public byte[] Logo { get; set; }
    }
}
