//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSC_Location
    {
        public int LocationID { get; set; }
        public string DeptName { get; set; }
        public string HospitalName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string ContactTel { get; set; }
        public string HospitalNameEng { get; set; }
        public string LocationCode { get; set; }
        public Nullable<bool> InActive { get; set; }
        public Nullable<int> BranchID { get; set; }
    }
}
