//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSC_Appointment
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<int> ResourceID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public string ServiceName { get; set; }
        public string PrepareContent { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string MRCode { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<byte> AppointmentType { get; set; }
        public Nullable<int> SubResourceID { get; set; }
        public string CreateBy { get; set; }
        public Nullable<long> ExamineID { get; set; }
        public Nullable<long> OnlineBookingID { get; set; }
        public string UpdateLog { get; set; }
        public string Phone { get; set; }
    }
}
