//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSC_Subject
    {
        public int SubjectID { get; set; }
        public string SubjectTitle { get; set; }
        public Nullable<byte> SubjectType { get; set; }
        public string SubjectTitle_Eng { get; set; }
        public Nullable<int> Group1 { get; set; }
        public Nullable<int> Group2 { get; set; }
        public Nullable<byte> AppointmentType { get; set; }
    }
}
