//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUT_Approval
    {
        public int ID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public int RequestType { get; set; }
        public string RequestNote { get; set; }
        public string RequestBy { get; set; }
        public Nullable<int> ObjectType { get; set; }
        public Nullable<int> ObjectID { get; set; }
        public string ObjectCode { get; set; }
        public string FileLink { get; set; }
        public Nullable<int> Status { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string ApprovedNote { get; set; }
        public string ActionLog { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<int> BranchID { get; set; }
    }
}
